### ISSUE TITLE
Content is not displayed 

### ISSUE THREAD

**Issue by fabiogeraci** [luizdepra/hugo-coder#730]
Error handling response: TypeError: Cannot read properties of null (reading 'codescript')
    at chrome-extension://iamhhblhmpldjchjecmapgoikpjmmfoe/content/content.js:4:18
site.webmanifest:1          Failed to load resource: the server responded with a status of 404 (Not Found)
site.webmanifest:1 Manifest: Line: 1, column: 5, Unexpected data after root element.
site.webmanifest:1          Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by luizdepra** [comment]
Hey, @fabiogeraci.

Could you please provide us more information about the issue?

But, this line `at chrome-extension://iamhhblhmpldjchjecmapgoikpjmmfoe/content/content.js:4:18` tells me that one of your browser extension is causing the issue. Try again on a private tab or disabling all extensions.

**Comment by fabiogeraci** [comment]
Hey,
thank you for the quick response. I tried, as you suggested on a private tab as well as on firefox with no extensions and the outcome is the same

Failed to load resource: the server responded with a status of 404 (Not Found)

I am not actually sure that the issue is the theme I tried a different theme and it was not rendering correctly the examplesite

**Comment by luizdepra** [comment]
Which version of Hugo are you using?

Well, try running `make demo` and then access `http://localhost:1313`.
It should display something like this: 
```
% make demo
hugo server -D --themesDir=../.. --source=exampleSite --bind 0.0.0.0
Start building sites …
hugo v0.102.3-b76146b129d7caa52417f8e914fc5b9271bf56fc+extended linux/amd64 BuildDate=2022-09-01T10:16:19Z VendorInfo=gohugoio
WARN 2022/11/03 15:22:29 The "twitter_simple" shortcode will soon require two named parameters: user and id. See "/home/luizdepra/dev/personal/web/hugo-coder/exampleSite/content/posts/rich-content.md:26:1"
WARN 2022/11/03 15:22:30 The "twitter_simple" shortcode will soon require two named parameters: user and id. See "/home/luizdepra/dev/personal/web/hugo-coder/exampleSite/content/posts/rich-content.pt-br.md:26:1"

                   | EN | PT-BR
-------------------+----+--------
  Pages            | 57 |    51
  Paginator pages  |  0 |     0
  Non-page files   |  0 |     0
  Static files     | 10 |    10
  Processed images |  0 |     0
  Aliases          | 23 |    19
  Sitemaps         |  2 |     1
  Cleaned          |  0 |     0

Built in 1414 ms
Watching for changes in /home/luizdepra/dev/personal/web/hugo-coder/{archetypes,assets,exampleSite,i18n,layouts,static}
Watching for config changes in exampleSite/config.toml, /home/luizdepra/dev/personal/web/hugo-coder/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 0.0.0.0)
```

(You might have problems to use the `make` command if you are using Window.)

**Comment by luochenxi** [comment]
> 

+ step 1:
`git clone https://github.com/luizdepra/hugo-coder` 

+ step 2:
`cd hugo-coder; hugo server -D --themesDir=../.. --source=exampleSite --bind 0.0.0.0`

+ show:
`GET http://localhost:1313/site.webmanifest 404 (Not Found) 
site.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.`

+ hugo version
`hugo v0.111.3+extended darwin/amd64 BuildDate=unknown `

**Comment by luizdepra** [comment]
@luochenxi where this error appears? In the browser console or on the commandline output?

I don't remember adding the `site.webmanifest` file into Hugo-Coder. Is this something custom?

**Comment by luochenxi** [comment]
@luizdepra  In the browser console.  I did not make any changes, but simply reproduced the steps above.
 
![image](https://user-images.githubusercontent.com/18586097/232366612-9d321df2-d548-479a-b427-ffa3b09865a1.png)
![image](https://user-images.githubusercontent.com/18586097/232366663-88840ef0-f1c7-4471-99a9-1229ccf1636c.png)

open http://localhost:1313/
 
In the browser console : 
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/18586097/232366730-4b2abfbb-e9d5-48aa-9c4b-3cc0d7acb9d1.png">

**Comment by luizdepra** [comment]
@luochenxi, right. I tried reproducing the issue and I didn't get the error.

Try accessing the page with other browsers or using the incognito mode. It looks like an extension or something is trying to access the file.

As far as I know, the `site.webmanifest` is a file used to provide information from a PWA to the browser. See [here](https://developer.mozilla.org/en-US/docs/Web/Manifest). So, doesn't make sense to Hugo Coder have it.

**Comment by cep21** [comment]
> So, doesn't make sense to Hugo Coder have it.

You reference the site.webmanifest [here](https://github.com/luizdepra/hugo-coder/blob/1fdac008175cba35ad5cbbac619671774c0e1afe/layouts/partials/head/custom-icons.html#L8).  Since it does not make sense for Hugo Coder to have it, should you remove that line from custom-icons.html in layouts?

**Comment by micchickenburger** [comment]
There are a few lines in this file that make assumption about existing content.  Some kind of settings should be checked before enabling these lines, else 404 errors are thrown in the browser console.

**Comment by lpanebr** [comment]
This also happens for me. I've just installed hugo and the theme.

I found that the file below uses "site.webmanifest" if there's no config for `.Site.Params.manifest`, I think:

https://github.com/luizdepra/hugo-coder/blob/70c0792f78b257c7b3c7614b2bc7dffa95f5143f/layouts/partials/head/custom-icons.html#L8
